apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api7-developer-portal.configMapName" . }}
  labels:
    {{- include "api7-developer-portal.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
