{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api7-developer-portal.secretName" . }}
  labels:
    {{- include "api7-developer-portal.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
