dashboard:
  image:
    tag: dev
    pullPolicy: IfNotPresent
dp_manager:
  image:
    tag: dev
    pullPolicy: IfNotPresent
developer_portal:
  image:
    tag: dev
    pullPolicy: IfNotPresent
fullnameOverride: api7ee-e2e
podSecurityContext:
  runAsUser: 0
dashboard_configuration:
  log:
    level: debug
  server:
    listen:
      disable: false
      host: '0.0.0.0'
      port: 7080
    tls:
      disable: false
      host: '0.0.0.0'
      port: 7443
    status:
      host: '0.0.0.0'
  developer_proxy:
    cache_failure_count: 256
    cache_failure_ttl: 1
    cache_success_count: 256
    cache_success_ttl: 1
dp_manager_configuration:
  api_call_flush_period: 1s
  server:
    status:
      host: '0.0.0.0'
  log:
    level: debug
prometheus:
  builtin: false
  server:
    persistence:
      enabled: false
postgresql:
  image:
    repository: api7/postgresql
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false
developer_portal_configuration:
  enable: true
  server:
    listen:
      host: '0.0.0.0'
      port: 4321
      tls:
        enabled: false
        key_file: '' # the file path of private key, (e.g. /app/certs/tls.key)
        cert_file: '' # the file path of certificate, (e.g. /app/certs/tls.crt)
    status:
      disable: false
      host: '127.0.0.1'
      port: 4322
  log:
    level: warn
    output: stderr
  database:
    dsn: 'postgres://api7ee:changeme@api7-postgresql:5432/api7ee'
    max_idle_conns: 2
    max_open_conns: 30
  console:
    addr: 'http://127.0.0.1:3000'
